const { OpenAI } = require("openai");

// Initialize OpenAI with your API key
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY, // Use the OpenAI API key from .env
});

// Function to generate summary using OpenAI
exports.generateSummary = async (text) => {
  try {
    // Define the prompt for GPT-3/4 summarization
    const prompt = `
      Summarize the following text into a concise and informative summary:

      ${text}
    `;

    // Send the request to OpenAI for summarization
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini", // Use GPT-4 model for better results (or GPT-3.5)
      messages: [{ role: "user", content: prompt }],
    });

    // Return the summary generated by GPT-4
    const summary = response.choices[0].message.content.trim();
    return summary;
  } catch (error) {
    console.error("Error generating summary:", error);
    throw new Error("Summary generation failed");
  }
};
